version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: npm
    directories:
      - /
      - /web
      - /worker
      - /shared
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      all:
        patterns:
          - "*"
